name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        colors: dark-tritanopia
        include-title: false
        top-icon: github
        max-languages: 15
        language-repository-exclusions:  awesome-windows-tweaks
        language-animation-speed: 20
        small-title: true
        show-border: false
      env:
        GITHUB_TOKEN: ${{secrets.token_sl}}
